//独立COOKIE文件     ck在``里面填写，多账号换行

let qmydtokenVal = `Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzMTgyNiwiZXhwIjoyMDUzNjQzMTgyNiwibmJmIjoxNjE0ODMxODI2LCJqdGkiOiJPQW5UcFpLS3VwaFU0UFQ2Iiwic3ViIjoxMTYyNjksInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.wPEMezJZWlZkF7JZ4Iyj1GOfL4HhyrTDT4MNzjRDOq4
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzNDk3NiwiZXhwIjoyMDUzNjQzNDk3NiwibmJmIjoxNjE0ODM0OTc2LCJqdGkiOiJ6c1Bwc2hjRnNPaDVkOTVpIiwic3ViIjoxMTYzMzUsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.0ON4gv8xvuP_8DIvgyzsjAnbaM5jQ5talpIi6ah1lis
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvcW15ZC55aWNoZW5ndy5jblwvYXBwc1wvbG9naW5cL3dlY2hhdCIsImlhdCI6MTYxNDgzNDkxMCwiZXhwIjoyMDUzNjQzNDkxMCwibmJmIjoxNjE0ODM0OTEwLCJqdGkiOiJ6aUpsanM2ZHZlNm9sTzBGIiwic3ViIjoxMTYzMzQsInBydiI6IjQxZGY4ODM0ZjFiOThmNzBlZmE2MGFhZWRlZjQyMzQxMzcwMDY5MGMifQ.qbQVfVmsroYIADYnpsF4SDjSC1EpG4azbvq8jzFbR6U`








let qmydcookie = {

    qmydtokenVal: qmydtokenVal,

}

module.exports = qmydcookie
